// Regenerates test/fixtures/gitconfig-golden.json.
//
// Run offline, by hand, when the case list changes:  node tools/generate-golden.mjs
// git is the only valid oracle for "what does git read from this file", but it is
// NOT a test-time dependency: the answers are committed, and the suite compares
// the parser against the committed table.
import { writeFile, mkdtemp, rm } from 'node:fs/promises';
import { execFileSync } from 'node:child_process';
import { tmpdir } from 'node:os';
import path from 'node:path';

const CASES = {
  'plain': '[core]\n\tfsmonitor = /tmp/x.sh\n',
  'no-spaces': '[core]\n\tfsmonitor=/tmp/x.sh\n',
  'tabs-and-spaces': '[core]\n   \tfsmonitor \t=  /tmp/x.sh  \n',
  'upper-section': '[CORE]\n\tFSMONITOR = /tmp/x.sh\n',
  'subsection': '[filter "lfs"]\n\tclean = git-lfs clean -- %f\n',
  'subsection-with-dot': '[diff "ipynb.v2"]\n\ttextconv = jupyter nbconvert\n',
  'quoted-value': '[core]\n\tfsmonitor = "/tmp/my x.sh"\n',
  'partial-quote': '[core]\n\tpager = "cur"l x\n',
  'escaped-quote': '[core]\n\tpager = "say \\"hi\\""\n',
  'escape-tab': '[core]\n\tpager = "a\\tb"\n',
  'escape-newline': '[core]\n\tpager = "a\\nb"\n',
  'escape-backslash': '[core]\n\tpager = "a\\\\b"\n',
  'continuation': '[core]\n\tfsmonitor = /tmp/\\\n\tx.sh\n',
  'comment-hash-spaced': '[core]\n\tfsmonitor = /tmp/x.sh # note\n',
  'comment-hash-tight': '[core]\n\tfsmonitor = /tmp/x.sh#note\n',
  'comment-semicolon': '[core]\n\tfsmonitor = /tmp/x.sh ; note\n',
  'comment-in-quotes': '[core]\n\tpager = "less # not a comment"\n',
  'key-on-section-line': '[core] fsmonitor = /tmp/x.sh\n',
  'implicit-true': '[core]\n\tbare\n',
  'section-twice': '[core]\n\tfilemode = true\n[core]\n\tfsmonitor = /tmp/x.sh\n',
  'key-twice': '[core]\n\tfsmonitor = true\n\tfsmonitor = /tmp/x.sh\n',
  'crlf': '[core]\r\n\tfsmonitor = /tmp/x.sh\r\n',
  'bom': '﻿[core]\n\tfsmonitor = /tmp/x.sh\n',
  'leading-blank-lines': '\n\n[core]\n\tfsmonitor = /tmp/x.sh\n',
  'empty-value': '[core]\n\tfsmonitor =\n',
};

const dir = await mkdtemp(path.join(tmpdir(), 'gs-golden-'));
const version = execFileSync('git', ['--version'], { encoding: 'utf-8' }).trim();
const out = { _note: [
  'Generated by tools/generate-golden.mjs. Do not edit by hand.',
  'git is the reference implementation for values it accepts. It refuses a malformed',
  'config, so the robustness cases in test/robustness.test.js have no oracle here:',
  'for those, "we fail towards the safe side" is a claim our own tests carry, not git.',
], _git: version, _generated: new Date().toISOString().slice(0, 10), cases: {} };

for (const [name, text] of Object.entries(CASES)) {
  const file = path.join(dir, `${name}.gitconfig`);
  await writeFile(file, text, 'utf-8');
  let listed = null, error = null;
  try {
    // -z: NUL-separated records of "key\nvalue". Without it a value containing a
    // newline is indistinguishable from the next key, which made the comparison lie.
    listed = execFileSync('git', ['config', '--file', file, '--list', '-z'], { encoding: 'utf-8' })
      .split('\0').filter(Boolean)
      .map(rec => { const i = rec.indexOf('\n'); return i === -1 ? rec + '=' : rec.slice(0, i) + '=' + rec.slice(i + 1); });
  } catch (err) {
    error = (err.stderr ?? String(err)).toString().trim().split('\n')[0];
  }
  out.cases[name] = { config: text, git: listed, gitError: error };
}
await rm(dir, { recursive: true, force: true });
await writeFile('test/fixtures/gitconfig-golden.json', JSON.stringify(out, null, 2) + '\n', 'utf-8');
console.log(`golden table: ${Object.keys(CASES).length} cases, ${version}`);
